// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmddHhPYoqaObINEJ8A4_1tWWYbEFKCzo',
    appId: '1:709716977497:web:05596a22d3f87ec95b0e48',
    messagingSenderId: '709716977497',
    projectId: 'mobilku-6454c',
    authDomain: 'mobilku-6454c.firebaseapp.com',
    storageBucket: 'mobilku-6454c.appspot.com',
    measurementId: 'G-HH1CL58GMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqgKY1ogpThVxf0tv6FVkKVqO7RBqPZ0',
    appId: '1:709716977497:android:f876f176b8402da75b0e48',
    messagingSenderId: '709716977497',
    projectId: 'mobilku-6454c',
    storageBucket: 'mobilku-6454c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqSKbDZzdcXDZAl_gR3qSI4ddil5EO80',
    appId: '1:709716977497:ios:cded531ec0d2fc725b0e48',
    messagingSenderId: '709716977497',
    projectId: 'mobilku-6454c',
    storageBucket: 'mobilku-6454c.appspot.com',
    iosClientId: '709716977497-s9un1rjg83e2ovaioic7l28ak6t5vo37.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcqSKbDZzdcXDZAl_gR3qSI4ddil5EO80',
    appId: '1:709716977497:ios:8960aaf28b0d8fed5b0e48',
    messagingSenderId: '709716977497',
    projectId: 'mobilku-6454c',
    storageBucket: 'mobilku-6454c.appspot.com',
    iosClientId: '709716977497-jeehgos9aogbsmk0171022mqae09ngpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMobil.RunnerTests',
  );
}
